# -*- coding: utf-8 -*-
"""game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsQ0bsD0xya540dBhma6SOBxejeV0QLJ
"""

Mini Project

# game.py
import random

class Game:
    def __init__(self):
        # Possible choix valides
        self.items = ['rock', 'paper', 'scissors']

    def get_user_item(self):
        # Demande à l'utilisateur de choisir un item jusqu'à ce qu'il donne une réponse valide
        while True:
            user_input = input("Veuillez choisir : rock, paper, ou scissors : ").lower()
            if user_input in self.items:
                return user_input
            else:
                print("Choix invalide, veuillez réessayer.")

    def get_computer_item(self):
        # Choisi un item aléatoirement pour l'ordinateur
        return random.choice(self.items)

    def get_game_result(self, user_item, computer_item):
        # Détermine le résultat du jeu
        if user_item == computer_item:
            return 'draw'
        elif (user_item == 'rock' and computer_item == 'scissors') or \
             (user_item == 'scissors' and computer_item == 'paper') or \
             (user_item == 'paper' and computer_item == 'rock'):
            return 'win'
        else:
            return 'loss'

    def play(self):
        # Fonction principale pour jouer une partie
        user_item = self.get_user_item()
        computer_item = self.get_computer_item()
        result = self.get_game_result(user_item, computer_item)

        # Affichage du résultat
        print(f"Vous avez choisi {user_item}. L'ordinateur a choisi {computer_item}.")
        if result == 'win':
            print("Vous gagnez !")
        elif result == 'loss':
            print("Vous perdez.")
        else:
            print("C'est une égalité!")

        return result

#################################################################################
#Le code ci-dessous est localisé dans un fichier py nommé rock-paper-scissors.py#
#################################################################################

def show_main_menu():
    # Affiche le menu principal
    print("Bienvenue au jeu Pierre-Feuille-Ciseaux !")
    print("1. Jouer une partie")
    print("2. Quitter")

def main():
    # Fonction principale pour gérer le flux du jeu
    while True:
        show_main_menu()
        choice = input("Veuillez faire votre choix (1 ou 2) : ")

        if choice == '1':
            game = Game()
            result = game.play()
            # Vous pouvez ajouter ici un résumé ou une boucle pour rejouer si vous le souhaitez
        elif choice == '2':
            print("Au revoir !")
            break
        else:
            print("Choix invalide, veuillez réessayer.")

if __name__ == "__main__":
    main()

