# -*- coding: utf-8 -*-
"""rock-paper-scissors.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChOX3t3vzT21dIEaGr3zBgj0Bab7oIuT
"""

# rock-paper-scissors.py

from game import Game

def show_main_menu():
    # Affiche le menu principal
    print("Bienvenue au jeu Pierre-Feuille-Ciseaux !")
    print("1. Jouer une partie")
    print("2. Quitter")

def main():
    # Fonction principale pour gérer le flux du jeu
    while True:
        show_main_menu()
        choice = input("Veuillez faire votre choix (1 ou 2) : ")

        if choice == '1':
            game = Game()
            result = game.play()
            # Vous pouvez ajouter ici un résumé ou une boucle pour rejouer si vous le souhaitez
        elif choice == '2':
            print("Au revoir !")
            break
        else:
            print("Choix invalide, veuillez réessayer.")

if __name__ == "__main__":
    main()
